import * as Joi from "joi";

export const envValidationSchema = Joi.object({
  NODE_ENV: Joi.string().valid("development", "production", "test").default("development"),
  PORT: Joi.number().default(3333),
  APP_BASE_URL: Joi.string().uri().required(),
  DATABASE_URL: Joi.string().uri({ scheme: ["postgresql", "postgres"] }).required(),
  DIRECT_DATABASE_URL: Joi.string().uri({ scheme: ["postgresql", "postgres"] }).optional(),
  SUPABASE_URL: Joi.string().uri().required(),
  SUPABASE_ANON_KEY: Joi.string().required(),
  SUPABASE_SERVICE_ROLE_KEY: Joi.string().required(),
  SUPABASE_JWT_SECRET: Joi.string().required(),
  UNSPLASH_ACCESS_KEY: Joi.string().optional(),
  FAL_API_KEY: Joi.string().optional(),
  ANTHROPIC_API_KEY: Joi.string().optional(),
  ANTHROPIC_MODEL: Joi.string().optional(),
  IMAGE_GEN_REFERENCE_WEIGHT: Joi.number().min(0).max(1).optional(),
  IMAGE_QA_THRESHOLD: Joi.number().min(0).max(10).optional(),
  RENDER_ENGINE_URL: Joi.string().uri().optional(),
  META_ADS_LIBRARY_ACCESS_TOKEN: Joi.string().optional(),
  ENABLE_COMPETITOR_SCRAPING: Joi.string().valid("true", "false").optional(),
  POSTIZ_API_URL: Joi.string().uri().optional(),
  POSTIZ_DATABASE_URL: Joi.string().uri({ scheme: ["postgresql", "postgres"] }).optional(),
  API_PUBLIC_URL: Joi.string().uri().optional(),
  LINKEDIN_CLIENT_ID: Joi.string().optional(),
  LINKEDIN_CLIENT_SECRET: Joi.string().optional(),
  LINKEDIN_API_VERSION: Joi.string().optional(),
  TOKEN_ENCRYPTION_KEY: Joi.string().hex().length(64).optional(),
  REDIS_URL: Joi.string().uri({ scheme: ["redis"] }).optional(),
}).unknown(true);
